version: '2'
services:
    db:
        image: postgres
    web:
        build: src/dotnet-compose
        command: dotnet run
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: http://*:5000
            ConnectionStrings__DefaultConnection: User ID=postgres;Host=db;Database=postgres